url: http://2020.code4lib.org
permalink: /:categories/:title
exclude: [node_modules]
exclude: [vendor]
repository: code4lib/2020.codelib.org
future: true
timezone: America/New_York
sass:
  sass_dir: assets/_scss
include:
  - .well-known
keep_files:
  - .dat
  - dat.json
